[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
bones_framework = { path = "../../framework_crates/bones_framework" }
bones_bevy_renderer = { path = "../../framework_crates/bones_bevy_renderer" }
