[package]
name                    = "bones_schema"
description             = "Simple runtime reflection system designed for scripting."
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
license.workspace       = true
repository.workspace    = true
documentation.workspace = true
categories.workspace    = true
keywords.workspace      = true

[features]
default = ["derive"]
serde   = ["dep:serde", "ulid/serde", "bones_utils/serde"]
derive  = ["bones_schema_macros"]
glam    = ["dep:glam"]

[dependencies]
bones_utils = { version = "0.3", path = "../bones_utils" }
ulid        = { version = "1.0" }
paste       = "1.0"

# Optional deps
bones_schema_macros = { version = "0.3", path = "./macros", optional = true }
glam                = { version = "0.24", optional = true }
serde               = { version = "1.0", features = ["derive"], optional = true }
sptr                = "0.3"

[[test]]
name              = "tests"
required-features = ["glam"]

[dev-dependencies]
serde_yaml = "0.9"
trybuild   = "1.0"
